### ISSUE TITLE
Clicking away from Create Game or Join Game should delete popup menu

### ISSUE THREAD

**Issue by BartMassey** [TeamDelightful/GlassPlateGame#124]
Right now, the states of the popup menus for Create Game and Join Game on the front page are completely disconnected from each other and are persistent. I would expect that a click anywhere off of a popup menu would cause the menu to disappear.

**Comment by kristinbell** [comment]
Bart, with your comments elsewhere, I'm thinking for the "Create Game" button we can just lose the drop down all together since you don't want the gameID displaying that early anyway, and we can just have a click of the "Create Game" button take the host to the deck selection/game page. This will prevent someone from just sitting on the "Create Game" button and creating a bunch of random games. We'll just need to fix the "Join Game" button and figure out how to link up the person who clicked "Create Game" with the actual game page. Sound okay?

**Comment by BartMassey** [comment]
Sounds good.

**Comment by BartMassey** [comment]
Looks great. Thanks!
