### ISSUE TITLE
Games are not gc-ed when abandoned / empty

### ISSUE THREAD

**Issue by BartMassey** [TeamDelightful/GlassPlateGame#126]
When a game is abandoned (goes to 0 players), the game is nonetheless kept around by the server and can still be re-joined any time before the server exits. This is kind of worst of both worlds. On the one hand (a), if games were persisted across server restarts, this would allow continuing a game after a sever crash, and provide a permanent record of all games played. On the other hand (b), if games were deleted when abandoned (including by disconnect), that would save server resources and help to prevent denial-of-service attacks on the server.

The special cases of a game abandoned before "Start Game" or before there is more than one player are worth careful consideration.

For now, I think that plan (b) is the correct one.

**Comment by kristinbell** [comment]
Yes. Currently if the person who started the game/picked the cards does a "dirty exit," meaning they just close the window instead of hitting the "Leave Game" button it will not delete the game itself. Otherwise, as far as I can tell it is deleting the games if the first person to use the game is leaving with the button. We hadn't accounted for if someone started the game but abandoned it. I think if we can get the new create game thing to work where the creator is taken immediately to the game page we might have a different way to solve this issue. In other words, if we can check for the creator to not be in the list of users, then if they are gone and no one else is in the list then we can delete? We are currently trying to figure out how to get the game to delete if the host has done a dirty delete, because we are using fetch/post and if we leave the page too soon it won't register. But we are looking into it. Thanks for the idea about checking to see if anyone is in the list of users.

**Comment by BartMassey** [comment]
You want to leave the game running if the creator has to exit early. Others may still be playing.

**Comment by kristinbell** [comment]
I think I got this working. Just have to test a little bit with everyone.
