### ISSUE TITLE
Layout has changed to vertical (top/bottom); not ok

### ISSUE THREAD

**Issue by BartMassey** [TeamDelightful/GlassPlateGame#155]
In the latest version of the code (commit a4abc86a543a2e6a065d7eb029f6ec7a2c4e4283) the layout of the game page has switched from messages left / playfield right to messages top / playfield bottom. Given screen widths vs heights, this doesn't work well: messages should be either left or right of playfield so that they can be easily followed while playing.

**Comment by kristinbell** [comment]
Unfortunately we made this change, because the pixi board was shoving the chat board off of the screen so it was unreadable on window resize...but only when we would go from larger to smaller (or maybe it was the reverse). Let me try to put the chat board on the right side to see if we can fix that issue. It might take a bit of reconfiguring time. Thanks for letting us know.

**Comment by kristinbell** [comment]
got it to work on the right side! yay! so on the larger size screens it is on the chat box is on the right now.
